### PR TITLE
fix for state.persist

### LINKED ISSUE #331: state.persist is broken in HA 2022.3
https://github.com/home-assistant/core/pull/66068 changed the signature of `async_restore_entity_added` from taking an entity `str` to taking a `RestoreEntity`

### PR DESCRIPTION
**Pull request by dlashua**
fixes #331

### CODE REVIEW

**Comment by dlashua** [comment]
The failing tests are due to the use of internal class properties externally.

The correct way to handle is it to write a class that extends RestoreEntity and provides methods to set these properties. However, as is, it should resolve the 2022.3 compatibility issues. Then, after some thought on how to implement this in a way that exposes entities to userland pyscripts, this temporary fix can be adjusted to fit in line with that plan.

**Comment by stefanuytterhoeven** [comment]
Made the changes to my state.py, and can confirm it works...

**Comment by craigbarratt** [comment]
@dlashua - thanks for the patch!  Couple of questions:

- is this backward compatible with older versions of HA?
- are there other breaking changes in HA 2022.3?

**Comment by dlashua** [comment]
> * is this backward compatible with older versions of HA?

I don't think so. `async_restore_entity_added` was modified to expect an object passed to it. It then accesses attributes of that object. Is there a way to detect HA version and use different code depending on the version?

> * are there other breaking changes in HA 2022.3?

According to the release notes, no. But, the issue fixed here is also not mentioned in the release notes, so maybe?

I've not upgraded to 2022.3 yet, due to a lack of time. I just recently upgraded to 2022.2.

**Comment by dlashua** [comment]
Oh my... all tests finally passed.

**Comment by craigbarratt** [comment]
I'm not sure how to detect the HA version, although hopefully it is easy.  One approach would be to use try/except clauses to handle the new and old cases (which has the advantage that we don't need to explicitly test for the HA version).

**Comment by dlashua** [comment]
After I finished fixing all the test failures, this will no longer load in Home Assistant.

ERROR (MainThread) [homeassistant.setup] Setup failed for pyscript: Integration not found.

But the files are in the right place (the same place they were in when I was testing the code changes). I have debug logging turned on and it's not providing any additional information. So... I'm not sure how I broke whatever is now broken.

I even deleted everything, recloned Home Assistant, and recloned the Pyscript component and I still have the same issue.

I'm out of time for now, perhaps @craigbarratt can figure out what went wrong?

**Comment by dlashua** [comment]
Apparently the devcontainer got corrupted somehow. I have resolved that issue and this loads fine now.

**Comment by dlashua** [comment]
This is now compatible with HASS Versions < 2022.3.0. I tested with 2022.2.9, but unless really old versions used some other method of restoring state, this should work.

**Comment by dlashua** [comment]
I am now successfully running this in my "production" Home Assistant on version 2022.2.9.

For those needing a quick fix until this issue is ironed out and merged, you can install the master branch of github.com/dlashua/pyscript. If you use HACS, you can add this repo as a custom repository (it will show up as `pyscript_dlashua`). Then remove `pyscript`, install `pyscript_dlashua` instead, and then restart Home Assistant (apparently, HACS will allow two repos to provide files in the same custom_component at the same time, so, don't install `pyscript_dlashua` before removing `pyscript` or unknown things could happen).

**Comment by dlashua** [comment]
I am now successfully running HASS 2022.3.1 without issues.

**Comment by craigbarratt** [comment]
Thanks for the fix

I'm going to upgrade some of the versions in `tests/requirements_test.txt`.

In particular, `pytest-homeassistant-custom-component` v0.7.0 is based on 2022.3.1 so the next step is to make sure all the tests run with that version.

**Pull request merged**
