### PR TITLE
test: tests can now be run in local virtualenv

### PR DESCRIPTION
**Pull request by fleXible**
Easy preparation and extremely fast test execution.
Pytest is now run as Github Action on push and pull-requests.

### CODE REVIEW

**Comment by craigbarratt** [comment]
Wow, thanks for doing this!

**Comment by fleXible** [comment]
You're welcome. I was well motivated because it was such a pain before to even get the tests running.

**Comment by craigbarratt** [comment]
I created a clean directory and went through the steps.  However, each of the tests failed with:
```
ModuleNotFoundError: No module named 'voluptuous'
```
After I installed `voluptuous` the tests ran fine.  Should `voluptuous` be in `requirements_test.txt`?  I'm surprised it doesn't get installed via the `pytest-homeassistant` requirement...

**Comment by fleXible** [comment]
It has to be a local issue of some sorts. Look at the automated test logs, it gets installed [pytest run logs](https://github.com/custom-components/pyscript/runs/1103857882).
Also on my local system it got installed automatically.

**Pull request merged**
