### PR TITLE
Fix access to config data now that we are using config flow

### PR DESCRIPTION
**Pull request by raman325**
This should resolve the issue we are discussing in #31. Since you said you can reproduce the issue @craigbarratt, can you test this and make sure it works? I would also test updating the config and doing a reload to make sure that the logic I changed works.

### CODE REVIEW

**Comment by raman325** [comment]
I don't think the test failure is related to this change but please tell me if that's not true.

Just to review the changes I have made since you mentioned that you don't know much about config flows - I have done a couple of things:
1. On HA load, the `configuration.yaml` gets loaded and then each integration runs through `async_setup`, which in `pyscript`s case initiates a config flow with the context being {"source": "import"} to let the config flow handler know that this is coming from configuration.yaml. The logic for import is to check for an existing entry (means this was already setup) and then updates it if any of the specified parameters ("allow_all_apps" and now "apps") change.
2. In all places I can find where the logic was expecting the config to be `{DOMAIN: {<data>}}`, I have updated it to refer to `config_entry.data` which will just return `<data>`
3. In the reload logic, after reloading `configuration.yaml`, if there is a `pyscript` config and it's config is different from the config entry's config, it calls the same logic as #1 which will update the config entry.

**Comment by raman325** [comment]
I've also made the update logic more generic. As long as `CONF_ALL_KEYS` contains all the keys that you expect, the logic will work for any key you add to the schema in the future

**Comment by raman325** [comment]
Alright, I've simplified the update logic so that it supports mixed configs (setting the config entry up through UI but adding apps through `configuration.yaml`). If the entry was set up through the UI, then it ignores updating `allow_all_imports` from `configuration.yaml` since it is optional in the config so may unintentionally be set to false during the update.

**Comment by craigbarratt** [comment]
Thanks for the PR and the updates.

I cloned `raman325:fix_config_flow` and I see two issues:
* sometimes on a cold start, pyscript setup fails to complete, with a warning
```
2020-10-12 11:23:21 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: pyscript
```
If I quit and start again, it comes up fine.  This happens if the yaml config was changed before starting.  If I put a log message at the start of `async_setup_entry` it doesn't get printed.
* On startup, `pyscript.config` uses regular `dict`; for example with this yaml:
```yaml
pyscript:
  allow_all_imports: true
  apps:
    app1:
      - val1: 10
      - val2: 21
  apps_list:
    entry1:
      - val1: 100
      - val2: 200
```
then `pyscript.config` is set to
```python
{
    "allow_all_imports": True,
    "apps": {"app1": [{"val1": 10}, {"val2": 21}]},
    "apps_list": {"entry1": [{"val1": 100}, {"val2": 200}]},
}
```
but on reload if the yaml config has changed, `pyscript.config` uses `OrderedDict`:
```python
{
    "allow_all_imports": True,
    "apps": OrderedDict(
        [("app1", [OrderedDict([("val1", 10)]), OrderedDict([("val2", 21)])])]
    ),
    "apps_list": OrderedDict(
        [("entry1", [OrderedDict([("val1", 100)]), OrderedDict([("val2", 200)])])]
    ),
}
```
It would be great if the reload case was the same as the cold start case (eg, regular `dict`).

**Comment by raman325** [comment]
It looks like the two issues are related - the setup only fails after the config entry has been updated with OrderedDicts.

When I call `await async_hass_config_yaml(hass)`, it's returning the config with OrderedDict's. I tested this with the last commit before I introduced config flow running the latest dev HA and the same thing occurs, so it's possible this has always been there but you didn't notice, or that something changed, although I couldn't figure out what that would be. Anyway, still investigating

**Comment by raman325** [comment]
OK the two weren't related. Fixed the timeout issue, but as far as I can tell, the OrderedDict's thing was always how the config was being pulled in. The difference is that with a config entry, on shutdown HA writes the data to disk and then it becomes a normal dictionary. I can get around this by doing a `json.loads(json.dumps(config))` which will always return a normal dictionary, but it seems kludgy. Thoughts?

**Comment by raman325** [comment]
I went ahead and forced it to always use a dictionary. All startup issues should be gone as well. Let me know if you run into anything else

**Comment by craigbarratt** [comment]
Thanks for converting the OrderedDict on reload.  I don't know a better way to do that.

Unfortunately I still see the first problem: pyscript fails to initialize if the yaml config was modified.  Can you replicate that?

**Comment by raman325** [comment]
I was not testing the right scenario to trigger the failure. I found where the call is failing and found that the line is unnecessary. This should be working 100% finally (hopefluly)

**Comment by craigbarratt** [comment]
Looks good!  Thanks for the quick followup and resolution.

**Comment by raman325** [comment]
Thanks for the extensive testing! It would be good to add some test coverage for these types of scenarios, I'm just not sure the best way to go about doing it, but if I think of one I will submit a new PR

**Comment by craigbarratt** [comment]
Agreed, but I'm not sure how to mock the yaml configuration.  I just added `mock-open` to `tests/requirements_test.txt` so I can add tests for module importing; perhaps that can mock the config file too.

Also, I finally figured out how to add pylint to pre-commit and github actions.  I just made a couple of very minor pylint fixes to the config flow.

**Comment by raman325** [comment]
Awesome! Thanks for the tweak and good catch on the tests

**Comment by craigbarratt** [comment]
I just released 0.31, which includes the config flow.  I then tested it with a new installation of HASS 0.117.0.dev0, installed HACS, then installed pyscript 0.31.  It doesn't start - it doesn't get as far as creating the `<config>/pyscript` directory.

Can you look at this please asap?

**Comment by craigbarratt** [comment]
Oops - I didn't add `pyscript:` to `config/configuration.yaml`.  After doing that, it starts now.  Sorry about the false alarm.

Just confirming that step is still necessary with config flow?

**Comment by craigbarratt** [comment]
While it does now show up under "Configuration", the pyscript card doesn't have a "Configure" button.  And it doesn't show up when you search for it.  So as far as I can tell, config flow is not working on a clean install.

**Comment by raman325** [comment]
@craigbarratt I just tested it and it is working as expected. To be clear, after installation, you still have to go to Config > Integrations, click on the add button in the bottom right, and then select pyscript. From there it should be straight forward to set it up (this is when you don't have `pyscript` in your `configuration.yaml` btw.

Regarding configure: That's only available to a subset of integrations. What we can do in the future is make it so people can add `apps` config parameters through the UI. The UI doesn't support it yet but I have seen requests for it so I think it will in the future

**Comment by raman325** [comment]
Also one thing to note, now that it's a config entry, to remove the integration you have to both delete the config entry from the UI and delete it from your `configuration.yaml` if that's how it was configured

**Comment by craigbarratt** [comment]
On a clean new install of HASS, HACS and pyscript, pyscript is not shown in Configuration -> Integrations -> "+".  There is no sign that config flow is working.

**Comment by raman325** [comment]
Try hard refreshing the front end and then try to add it. I had this problem in the past when I was developing config flows for other integrations

**Comment by craigbarratt** [comment]
Ok, I opened an incognito chrome window, logged in, and it does now show pyscript in Configuration -> Integrations -> "+".

However, after checking "allow all imports", I get this error:
```
Aborted
[%key:common::config_flow::abort::single_instance_allowed%]
```
Is that because I already set up the yaml configuration?

**Comment by raman325** [comment]
Yes. That should show a more friendly error but I made a mistake. Core integrations can use common strings HA provides, but I guess custom integrations can't use them. I'll submit a PR to fix that

**Comment by craigbarratt** [comment]
Ok, thanks.  I'll try a fresh install and make sure I use a clean browser session.

**Comment by craigbarratt** [comment]
I tried a clean install (HASS, HACS, pyscript) with a new incognito browser and I have the same problem.  After installing pyscript with HACS, and restart HASS, Configuration -> Integrations -> "+" doesn't show pyscript.  Pyscript doesn't initialize.

**Comment by raman325** [comment]
Did you have the incognito browser open in the frontend before you installed pyscript with HACS? The frontend does some pretty heavy caching, it's best to do a hard refresh of the page after installing a new integration

**Comment by craigbarratt** [comment]
Yes.  I just quit the incognito window and started another one.  It worked with a new browser session - I can find pyscript, and I do get prompted for "allow all imports".  Wow, that's not a great user experience, but this appears to be an issue outside of pyscript.

The pyscript card now shows in Configuration -> Integrations.  However, it doesn't have an "options" link like HACS does.  How do you change the config setting for "allow all imports" after the first time?

**Comment by raman325** [comment]
I just tried a clean install myself and found it: 
image

**Comment by raman325** [comment]
Well, your reload logic doesn't handle updates to `allow_all_imports` even through configuration.yaml. I am happy to add that and to add support to the UI to make that change if that's desirable.

**Comment by raman325** [comment]
The only place you configure the `allow_all_imports` parameter is here: https://github.com/custom-components/pyscript/blob/master/custom_components/pyscript/__init__.py#L68 and the only place where it gets accessed is here: https://github.com/custom-components/pyscript/blob/master/custom_components/pyscript/eval.py#L724

I can add in support to the UI to make this changeable, but that would require changes to the reload service as well

**Comment by craigbarratt** [comment]
Ah good point.  At least with the yaml setting you can change it and then re-start HASS.  But, yes, adding that to config flow and also reload would be excellent.

**Comment by raman325** [comment]
no worries! I can work on that next. If I get `hass.data[DOMAIN][CONF_ALLOW_ALL_IMPORTS]` updated, will the integration pick it up? I guess the question is, does `AstEval` get initialized on every run, or is it a persistent class that gets accessed?

**Comment by craigbarratt** [comment]
That would be great - no rush.  Most `AstEval` instances will get recreated during reload, although not for Jupyter sessions which persist.  I'll change the code so it doesn't save the value when `AstEval` is created - it can simply check the config value when it executes each `import` statement.

**Comment by raman325** [comment]
I'll handle that in my update

**Pull request merged**
