### PR TITLE
added hass_is_global config parameter

### LINKED ISSUE #46: Feature Request: access to sunset/sunrise in function
This works, but it's complicated to write and follow:
```python
@state_trigger('binary_sensor.dark == "on"')
@time_active("range(sunrise - 120min, sunset + 120min)")
def turn_on_dark():
    turn_on()

@state_trigger('binary_sensor.downstairs_occupied == "on" and binary_sensor.dark == "on"')
def turn_on_occupied():
    turn_on()

@state_trigger('binary_sensor.downstairs_occupied == "off"')
@time_active("range(sunset + 120min, sunrise - 120min)")
def turn_off_notoccupied():
    turn_off()

@state_trigger('binary_sensor.dark == "off"')
def turn_off_notdark():
    turn_off()

@time_trigger('startup')
@state_active('binary_sensor.dark == "on"')
@time_active("range(sunrise - 120min, sunset + 120min)")
def turn_on_startup_dark():
    turn_on()

@time_trigger('startup')
@state_active('binary_sensor.downstairs_occupied == "on" and binary_sensor.dark == "on"')
def turn_on_startup_occupied():
    turn_on()

@time_trigger('startup')
@state_active('binary_sensor.downstairs_occupied == "off"')
@time_active("range(sunset + 120min, sunrise - 120min)")
def turn_off_startup_notoccupied():
    turn_off()

@time_trigger('startup')
@state_active('binary_sensor.dark == "off"')
def turn_off_startup_notdark():
    turn_off()
```

I would prefer this:
```python
import datetime

@time_trigger('startup')
@state_trigger('True or binary_sensor.dark or binary_sensor.downstairs_occupied')
def set_lights():
    today = datetime.datetime.today()
    start_time = today.replace(hour=5, minute=0) # would like sunrise - 120min
    end_time = today.replace(hour=22, minute=0) # would like sunset + 120min

    if binary_sensor.dark == "off":
        turn_off()
        return

    if start_time < datetime.datetime.now() < end_time:
        turn_on()
        return

    if binary_sensor.downstairs_occupied == "on":
        turn_on()
        return

    turn_off()
```

However, as you can see in the code comments, there's not an easy way to get to sunrise/sunset offsets.

### PR DESCRIPTION
**Pull request by craigbarratt**
This PR adds a config parameter `hass_is_global` (default False), which if set provides `hass` as a global variable in all pyscript contexts.

@raman325 and @dlashua - I invited you to the forked repository.  Please review and feel free to push any changes to `craigbarratt/pyscript-hass-is-global`, or just comment here.

This will resolve #46.

### CODE REVIEW

**Comment by raman325** [comment]
I just pushed the change I had suggested here: https://github.com/custom-components/pyscript/pull/42#issuecomment-713189490

**Comment by craigbarratt** [comment]
Thanks!  Should that also be done in `__init__.py` (it's aways used `cv.boolean`)?

**Comment by raman325** [comment]
no `cv.boolean` can be used there because the backend is aware of the custom config validators that HA provides. The issue is that the serializer that delivers the schema to the frontend (for config and option flows) was not aware of the custom validator before I submitted that PR, so it doesn't know what to do and throws an error instead of showing a form.

**Comment by craigbarratt** [comment]
Ok, thanks for the explanation.

**Comment by dlashua** [comment]
I've loaded this branch and it seems to work fine with no issues. I haven't found anything interesting to do with `hass` just yet, but the things I expect to be there are there and are usable.

**Comment by craigbarratt** [comment]
Thanks for the feedback and fixes.  I just released 0.32 (which has the HASS restart fix, config improvements from @raman325 and `@state_trigger` support for multiple arguments, lists and plain state variables to mean any).  I'm going to merge this and we have time to test and tweak if necessary.

**Comment by dlashua** [comment]
excellent, I'll pull master now so it gets a good test run.

**Pull request merged**
