### PR TITLE
add function entity_ids that returns all entities

### LINKED ISSUE #12: add function 'entity_ids'
Right now I cannot figure out how to get a list of all defined entities.

Maybe there could be a function
```python
def entity_ids(domain: str = None) -> List[str]:
    """Returns a list of all entity_ids in a domain. If None, all entity_ids are returned."""
```

### PR DESCRIPTION
**Pull request by basnijholt**
Closes #12

### CODE REVIEW

**Comment by basnijholt** [comment]
I've tested this and it works as intended :tada:

**Comment by basnijholt** [comment]
@craigbarratt I rebased and tested that it still works.

**Comment by craigbarratt** [comment]
Ok, thanks.  We might change this when we address issues #9 and #11.

**Comment by craigbarratt** [comment]
I replaced `entity_ids()` with `state.names()` in commit 7c087e7.

**Pull request merged**
